networks:
  app-network:
    external: true

services:
  front:
    build:
      dockerfile: apps/front/Dockerfile
    env_file:
      - ./apps/front/.env
    networks:
      - app-network
    environment:
      - API_URL=http://api:8080
      - NEXT_PUBLIC_API_URL=http://localhost/api