import './globals.css';
import type { Metadata } from 'next';
import NavBar from './_components/NavBar';
import TopBar from './_components/TopBar';
import RootProvider from './providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <RootProvider>
          <TopBar />
          <div className="flex grow">
            <NavBar />
            <div className="basis-full">{children}</div>
          </div>
        </RootProvider>
      </body>
    </html>
  );
}
