import './globals.css';
import type { Metadata } from 'next';
import RootProvider from './providers';
import { Inter } from 'next/font/google';
import { cn } from '@/lib/utils';
import { SidebarProvider } from '@/components/ui/sidebar';
import AppSidebar from '@/components/app-sidebar/app-sidebar';
import AppTopBar from '@/components/app-topbar/app-topbar';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        'h-full',
        'antialiased',
        'font-sans',
        'font-sans',
        inter.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <RootProvider>
          <SidebarProvider>
            <AppSidebar />
            <div className="flex-col w-full flex flex-1">
              <AppTopBar />
              <main className="flex-1 p-4">{children}</main>
            </div>
          </SidebarProvider>
        </RootProvider>
      </body>
    </html>
  );
}
