networks:
  app-network:
    external: true

services:
  redis:
    image: redis:8.6-alpine
    restart: always
    env_file:
      - ./infra/redis/.env
    networks:
      - app-network
  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data
    networks:
      - app-network

volumes:
  redis-insight: